import { createClient } from '@supabase/supabase-js'
export const supabase = createClient('https://tvyczphndaxjkjpjklci.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2eWN6cGhuZGF4amtqcGprbGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0MjQxMDgsImV4cCI6MjA5NjAwMDEwOH0.VC2psgzzBXz46jmwBEnUBUmGdDo7gVbgI_OHpoQsA0I')
